development:
 adapter: mysql2
 database: pocSinatra_development
 username: root
 password:
 host: localhost
 pool: 5


test:
 adapter: mysql2
 database: pocSinatra_test
 username: root
 password:
 host: localhost
 pool: 5